debug-mode: false                                             # Enable or disable debug mode.
use-discord-webhook: true                                     # Enable or disable Discord Webhook integration.
discord-webhook-url: "[Discord Webhook URL]"                  # Discord Webhook URL.